server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

## 配置文件给实体注入值
#student:
#  name: zs
#  age: 23
#  sex: true
#  birthday: 2020/10/1
#  location: {province: 湖北,city: 武汉, zone: 洪山}
#  hobbies: [足球, 篮球]
#  skills: [编程, 金融]
#  pet:
#    nickName: wc
#    strain: hsq
#person:
#  lastName: Mary
#  age: 16
#  birthDate: 2004/01/01
#  maps: {one:1,two:2,three:3}
#  lists:
#    - 1
#    - 2
#    - 3
#  pet:
#    name: wangcai
#    age: 3
